#!/bin/bash

# This will tell me where the script is, regardless of where it is being called
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This gets around the fact that debian doesn't have a symlink for
# python2-> python
if hash python2 2> /dev/null; then
    PYTHON=python2
else
    PYTHON=python
fi

#This calls the installed fabric (which was installed to the user account)
cd ${DIR}/fabric-scripts
$PYTHON call-fabric.py "$@"
