scp -P 22 dgi12.xml root@mamba1:/root/MST/FREEDM/Broker/adapter.xml
scp -P 22 dgi4.xml root@mamba1:/root/MST/FREEDM/Broker/adapter2.xml
scp -P 22 freedm.cfg root@mamba1:/root/MST/FREEDM/Broker/freedm.cfg
scp -P 22 topology.cfg root@mamba1:/root/MST/FREEDM/Broker/topology.cfg
scp -P 22 dgi1.xml root@mamba2:/root/MST/FREEDM/Broker/adapter.xml
scp -P 22 dgi13.xml root@mamba2:/root/MST/FREEDM/Broker/adapter2.xml
scp -P 22 freedm.cfg root@mamba2:/root/MST/FREEDM/Broker/freedm.cfg
scp -P 22 topology.cfg root@mamba2:/root/MST/FREEDM/Broker/topology.cfg
scp -P 22 dgi2.xml root@mamba3:/root/MST/FREEDM/Broker/adapter.xml
scp -P 22 dgi14.xml root@mamba3:/root/MST/FREEDM/Broker/adapter2.xml
scp -P 22 freedm.cfg root@mamba3:/root/MST/FREEDM/Broker/freedm.cfg
scp -P 22 topology.cfg root@mamba3:/root/MST/FREEDM/Broker/topology.cfg
scp -P 22 dgi8.xml root@mamba4:/root/MST/FREEDM/Broker/adapter.xml
scp -P 22 dgi5.xml root@mamba4:/root/MST/FREEDM/Broker/adapter2.xml
scp -P 22 freedm.cfg root@mamba4:/root/MST/FREEDM/Broker/freedm.cfg
scp -P 22 topology.cfg root@mamba4:/root/MST/FREEDM/Broker/topology.cfg
scp -P 22 dgi3.xml root@mamba5:/root/MST/FREEDM/Broker/adapter.xml
scp -P 22 dgi5.xml root@mamba5:/root/MST/FREEDM/Broker/adapter2.xml
scp -P 22 dgi7.xml root@mamba5:/root/MST/FREEDM/Broker/adapter3.xml
scp -P 22 freedm.cfg root@mamba5:/root/MST/FREEDM/Broker/freedm.cfg
scp -P 22 topology.cfg root@mamba5:/root/MST/FREEDM/Broker/topology.cfg
scp -P 22 dgi9.xml root@mamba6:/root/MST/FREEDM/Broker/adapter.xml
scp -P 22 dgi6.xml root@mamba6:/root/MST/FREEDM/Broker/adapter2.xml
scp -P 22 dgi11.xml root@mamba6:/root/MST/FREEDM/Broker/adapter3.xml
scp -P 22 freedm.cfg root@mamba6:/root/MST/FREEDM/Broker/freedm.cfg
scp -P 22 topology.cfg root@mamba6:/root/MST/FREEDM/Broker/topology.cfg
